config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'home/index'
  root to: 'homes#index'
  devise_for :users, skip: [:sessions]
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    get 'signup', to: 'devise/registrations#new', as: :new_user
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged

    self.per_page = 10

    belongs_to :owner, class_name: 'User', foreign_key: :owner_id
    validates :title, presence: true
    validates :event_type,:start_at, :end_at, presence: true
    validates :description, presence: true, length: { minimum: 5 }
    validate :end_at_after_start_at

    private

    def end_at_after_start_at
        return if end_at.blank? || start_at.blank?

        if end_at < start_at
            errors.add(:end_at, "must be after start date")
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

has_many :events, dependent: :destroy, foreign_key: :owner_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.paginate(page: params[:page], per_page: 10)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :description, :event_type, :start_at, :end_at)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @events = Event.paginate(page: params[:page], per_page: 10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
    def owner?(event)
        return true if event.owner == current_user

        return false
    end

    def active?(event)
        return true if event.start_at < Time.current && event.end_at > Time.current

        return false
    end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, autofocus: true, autocomplete: "title", class: 'form-control form-width' %>
  </div>
    <div class="field">
    <%= f.label :description, 'Description' %>
    <%= f.text_area :description, class: 'form-control form-width' %>
  </div>
  <div class="field">
    <%= f.label :event_type %>
    <%= f.select(:event_type, options_for_select([["Free", "free"], ["Paid", "paid"]]))%>
  </div>

  <div>
  <div class="field">
      <p>Select Dates to make event active</p>
    <%= f.label :start_at %>
    <%= f.datetime_select :start_at, :ampm => true, class: 'form-control' %>
  </div>
  <div class="field">
      <%= f.label :end_at %>
      <%= f.datetime_select :end_at, :ampm => true, class: 'form-control' %>
  </div>
  </div>

    <div class="actions">
      <%= f.submit "Create Event", class: "btn btn-primary rounded-0 mt-2" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h4 class="pad">Events</h4>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Owner</th>
      <th>Event Status</th>
      <th>Event Type</th>
      <th>show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
  <% if !@events.blank? %>
  <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.title, event%></td>
        <td><%= event.owner.name%></td>
        <%if active? event%>
        <td>Active</td>
        <%else%>
        <td>InActive</td>
        <%end%>
        <td><%= event.event_type%></td>
        <%if owner? event%>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>      
        <%end%>
      </tr>
    <% end %>
  <% else %>
    No Events Yet
  <%end%>
  </tbody>
</table>

<br>
<%= will_paginate @events %>
<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-header">
    Event Details
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @event.title%></h5>
    <p class="card-text"><%= @event.description%></p>
  </div>
</div>
<p><b>Owner:</b>  <%= @event.owner.name%></p>
<p><b>Event Type:</b>  <%= @event.event_type%></p>
<p><b>Event Status:</b>  <%if active? @event%>
           Active
          <%else%>
          InActive
          <%end%></p>
<p><b>Event Start Date:</b>  <%= @event.start_at.strftime("%B %d, %Y")%></p>
<p><b>Event End Date:</b>  <%= @event.end_at.strftime("%B %d, %Y")%></p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="pad">All Events</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Owner</th>
      <th>Event Status</th>
      <th>Event Type</th>
      <th>show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
  <% if !@events.blank? %>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.title, event%></td>
        <td><%= event.owner.name%></td>
        <%if active? event%>
        <td>Active</td>
        <%else%>
        <td>InActive</td>
        <%end%>
        <td><%= event.event_type%></td>
        <%if owner? event%>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>      
        <%end%>
      </tr>
    <% end %>
    <% else %>
    No Events Yet
  <%end%>
  </tbody>
</table>
<%= will_paginate @events %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg custom-navbar">
  <div class="container"> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" <%= link_to "TIX", root_path %> </a>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" <%= link_to "Home", root_path %> </a> <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Events", events_path %> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "New Events", new_event_path %> </a>
        </li>
      </ul>
      <% if user_signed_in?%>
     <a class="nav-link" <%= link_to "Log out", destroy_user_session_path, method: :delete %></a>
      <% else %>
      <a class="nav-link" <%= link_to "Sign up", new_user_path %></a>
      <a class="nav-link" <%= link_to "Sign in", new_user_session_path %></a>
      <% end%>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render 'layouts/nav' %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  </body>
</html>